{% set version = "2.2.31" %}
{% set commit = "76c10dc2f2ffeb2977648379e60b33f09ef66989" %}

package:
  name: libhdfs3
  version: {{ version }}

source:
  git_url: https://github.com/PivotalRD/libhdfs3.git
  git_tag: {{ commit }}

build:
  number: 2
  # This package is a dependency of hdfs3, which is primarily used with HDFS on Linux.
  skip: True  # [not linux]
  run_exports:
    # unknown.  Leaving defaults.
    - {{ pin_subpackage('libhdfs3') }}

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libprotobuf
    - libgsasl
    - libntlm
    - libuuid
    - libxml2
    - krb5
    - libboost  {{ boost }}

test:
  commands:
    - test -f $PREFIX/lib/libhdfs3.so
    - conda inspect linkages -p $PREFIX libhdfs3

about:
  home: https://github.com/PivotalRD/libhdfs3
  license: Apache 2.0
  summary: A Native C/C++ HDFS Client

extra:
  recipe-maintainers:
    - koverholt
    - martindurant
    - mrocklin
