{% set name = "libhdfs3" %}
{% set version = "2.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/ContinuumIO/{{ name }}-downstream.git
  git_tag: dc504af4a2445e9db836d3af9781ccc76c3856f2
  patches:
    - patches/CMakeLists.txt.diff
    - patches/84ebda7d.patch
    - patches/cmake-minimum-req-version.patch
    - patches/missing-namespace-string-npos.patch

build:
  number: 8
  # This package is a dependency of hdfs3, which is primarily used with HDFS on Linux.
  skip: true  # [not linux]
  run_exports:
    # Unknown. Leaving defaults.
    - {{ pin_subpackage(name) }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.5
    - git
    - make
  host:
    - libprotobuf {{ libprotobuf }}
    - libgsasl {{ libgsasl }}
    - libntlm {{ libntlm }}
    - libuuid {{ libuuid }}
    - libxml2 {{ libxml2 }}
    - libkrb5 {{ libkrb5 }}
    - libboost  {{ libboost }}
    - openssl {{ openssl }}
    - libcurl {{ libcurl }}
  run:
    - {{ pin_compatible('libboost') }}

test:
  commands:
    # Test header files
    - test -f $PREFIX/include/hdfs/BlockLocation.h
    - test -f $PREFIX/include/hdfs/DirectoryIterator.h
    - test -f $PREFIX/include/hdfs/Exception.h
    - test -f $PREFIX/include/hdfs/FileStatus.h
    - test -f $PREFIX/include/hdfs/FileSystem.h
    - test -f $PREFIX/include/hdfs/FileSystemStats.h
    - test -f $PREFIX/include/hdfs/InputStream.h
    - test -f $PREFIX/include/hdfs/OutputStream.h
    - test -f $PREFIX/include/hdfs/Permission.h
    - test -f $PREFIX/include/hdfs/XmlConfig.h
    - test -f $PREFIX/include/hdfs/hdfs.h
    # Test library files
    - test -f $PREFIX/lib/libhdfs3.so
    - test -f $PREFIX/lib/libhdfs3.so.1
    - test -f $PREFIX/lib/libhdfs3.so.2.2.31
    - test -f $PREFIX/lib/pkgconfig/libhdfs3.pc
    # Test linkages
    - conda inspect linkages -p $PREFIX libhdfs3

about:
  # The original GitHub repo at https://github.com/PivotalRD/libhdfs3 is not
  # available anymore.
  home: https://github.com/ContinuumIO/libhdfs3-downstream
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A Native C/C++ HDFS Client
  description: |
    The Hadoop Distributed File System (HDFS) is a distributed file system designed to run on commodity hardware.
    HDFS is highly fault-tolerant and is designed to be deployed on low-cost hardware.
    HDFS provides high throughput access to application data and is suitable for applications that have large data sets.
  doc_url: https://github.com/ContinuumIO/libhdfs3-downstream/blob/master/libhdfs3/README.md
  dev_url: https://github.com/ContinuumIO/libhdfs3-downstream

extra:
  recipe-maintainers:
    - koverholt
    - martindurant
    - mrocklin
